-- Generated from generator/demo_specs/aws-indonesia-palm-oil-precision-ag.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-indonesia-palm-oil-precision-ag
-- This is the schema that is actually deployed for ID_PALM_OIL_PRECISION_AG.

-- Alerts fire on the bottom tail of FFB Yield (Avg)
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_FFB_YIELD_AVG) AS T
  FROM RAW.IOT_SENSORS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_FFB_YIELD_AVG <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_FFB_YIELD_AVG), 2) AS AVG_FFB_YIELD,
  ROUND(AVG(f.KPI_FERTILIZER_EFFICIENCY), 2) AS AVG_FERTILIZER_EFFICIENCY,
  ROUND(AVG(f.KPI_OER_RATE), 2) AS AVG_OER_RATE,
  ROUND(AVG(f.KPI_HARVEST_INTERVAL), 2) AS AVG_HARVEST_INTERVAL,
  ROUND(AVG(f.KPI_PALM_AGE_AVG), 2) AS AVG_PALM_AGE
FROM RAW.IOT_SENSORS f
JOIN RAW.AGRONOMIST_DOCS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_FFB_YIELD_AVG), 2) AS AVG_FFB_YIELD,
  ROUND(AVG(f.KPI_FERTILIZER_EFFICIENCY), 2) AS AVG_FERTILIZER_EFFICIENCY,
  ROUND(AVG(f.KPI_OER_RATE), 2) AS AVG_OER_RATE,
  ROUND(AVG(f.KPI_HARVEST_INTERVAL), 2) AS AVG_HARVEST_INTERVAL,
  ROUND(AVG(f.KPI_PALM_AGE_AVG), 2) AS AVG_PALM_AGE
FROM RAW.IOT_SENSORS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_FFB_YIELD_AVG) AS KPI_FFB_YIELD_AVG, AVG(KPI_FERTILIZER_EFFICIENCY) AS KPI_FERTILIZER_EFFICIENCY, AVG(KPI_OER_RATE) AS KPI_OER_RATE, AVG(KPI_HARVEST_INTERVAL) AS KPI_HARVEST_INTERVAL, AVG(KPI_PALM_AGE_AVG) AS KPI_PALM_AGE_AVG FROM RAW.IOT_SENSORS),
     en AS (SELECT SUM(KPI_REPLANTING_TARGET) AS KPI_REPLANTING_TARGET, SUM(KPI_ESTATES_MONITORED) AS KPI_ESTATES_MONITORED FROM RAW.AGRONOMIST_DOCS)
  SELECT 1 AS SORT_ORDER, 'FFB Yield (Avg)' AS TITLE, KPI_FFB_YIELD_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FFB_YIELD_AVG), 1) AS DECIMAL(38,1))) || ' ' || 'T/ha' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Fertilizer Efficiency' AS TITLE, KPI_FERTILIZER_EFFICIENCY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FERTILIZER_EFFICIENCY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Replanting Target' AS TITLE, KPI_REPLANTING_TARGET AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_REPLANTING_TARGET) / 1000)) AS DECIMAL(38,0))) || 'K' || ' ' || 'ha' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Estates Monitored' AS TITLE, KPI_ESTATES_MONITORED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ESTATES_MONITORED)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'OER Rate' AS TITLE, KPI_OER_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_OER_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Harvest Interval' AS TITLE, KPI_HARVEST_INTERVAL AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_HARVEST_INTERVAL)) AS DECIMAL(38,0))) || ' ' || 'days' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Palm Age (Avg)' AS TITLE, KPI_PALM_AGE_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PALM_AGE_AVG)) AS DECIMAL(38,0))) || ' ' || 'yrs' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
