-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Precision Agriculture Analytics
-- ============================================================================
USE DATABASE PALM_OIL_PRECISION_AG;
USE SCHEMA ML;

-- ML.FORECAST: FFB_YIELD_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.FFB_YIELD_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.HARVEST_FORECAST_INPUT'),
  SERIES_COLNAME => 'BLOCK_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.FFB_YIELD_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.FFB_YIELD_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: YIELD_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.YIELD_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.BLOCK_YIELD_PERFORMANCE'),
  SERIES_COLNAME => 'BLOCK_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.YIELD_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.YIELD_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.BLOCK_YIELD_PERFORMANCE'), SERIES_COLNAME => 'BLOCK_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

