-- ============================================================================
-- 99_RESET.SQL — Reset Precision Agriculture Analytics to clean demo state
-- ============================================================================
USE DATABASE PALM_OIL_PRECISION_AG;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_IOT SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_YIELD SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_RECOMMENDATIONS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.BLOCK_YIELD_PERFORMANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.SOIL_NUTRIENT_STATUS REFRESH;
ALTER DYNAMIC TABLE CURATED.HARVEST_FORECAST_INPUT REFRESH;
ALTER DYNAMIC TABLE CURATED.FERTILIZER_ROI REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM PALM_OIL_PRECISION_AG.RAW.BLOCKS → 800
-- SELECT COUNT(*) FROM PALM_OIL_PRECISION_AG.RAW.IOT_SENSORS → 500000
-- SELECT COUNT(*) FROM PALM_OIL_PRECISION_AG.RAW.HARVEST_RECORDS → 200000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_GENERATE_RECOMMENDATIONS RESUME;
ALTER TASK IF EXISTS APP.TASK_FORECAST_YIELD RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_IOT RESUME;
